title: ZoZou Gallery
author: ZoZou
email: 664412383@qq.com
description: >-
  收集一些喜欢的图片、照片。

social:
  twitter: ZoZou02
  github: ZoZou02

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
