title: ZoZou Gallery
author: ZoZou
email: 664412383@qq.com
description: >-
  黑神话：悟空 图集

social:
  twitter: zozou_02
  github: ZoZou02

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true