title: ZoZou Gallery
author: ZoZou
email: 664412383@qq.com
description: >-
  黑神话：悟空 图集

social:
  twitter: zozou_02
  github: ZoZou02

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2

collections:
  images:
    output: true

# 分页
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true